name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - master

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Setup - python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Setup - dependencies
      run: |-
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Build
      run: |-
        make publish

    - name: Deploy
      run: |-
        gsutil -m rsync -R output gs://$GCS_BUCKET
